apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
      # annotations:
      #   linkerd.io/inject: enabled     
    spec:
      containers:
      - name: http-server
        image: restvsgrpc-rest-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_HTTP_PORTS
          value: "3001"
        - name: ASPNETCORE_URLS
          value: "http://+:3001"    
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  selector:
    app: http-server
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
